/*
Signal test program
*/
#include "PearlIncludes.h"

static pearlrt::FixedRangeSignal _overfl;
pearlrt::Signal *generalized_overfl = &_overfl;


static pearlrt::FixedDivideByZeroSignal _div0;
pearlrt::Signal *generalized_div0 = &_div0;

static pearlrt::ArithmeticSignal _arith;
pearlrt::Signal *generalized_arith = &_arith;

extern pearlrt::Signal *generalized_overfl;
extern pearlrt::Signal *generalized_div0;
extern pearlrt::Signal *generalized_arith;

SPCTASK(TASK1);

void _x(pearlrt::Task * me, pearlrt::Fixed<15> p) {
   pearlrt::Fixed<15> _k;

   //[ generated from ON statements in PROC
   static pearlrt::ScheduleSignalAction sigActions[] = {
		pearlrt::ScheduleSignalAction(generalized_arith),
		pearlrt::ScheduleSignalAction(generalized_overfl),
		pearlrt::ScheduleSignalAction(generalized_div0)};

   const size_t NBROFSIGACTIONS = 
		sizeof(sigActions)/sizeof(sigActions[0]);

   enum signalIndex{index_arith, index_overfl, index_div0};
   //]

   //[ generated due to goto in signal handler
   static void * labels[]={&&normalStart, &&label_exit,&&label_restart};
   enum signalGoto{noSignal1=0, index_exit, index_restart};
   int sigGoto = 0;

restart:
   goto *labels[sigGoto];
   //]

normalStart:    
   printf("------------------\n");

   //[ autogenerated due to ON statements in PROC
   try {
   //]

      _k = pearlrt::Fixed<15>(2);

label_restart:

      //[ generated from ON
      sigActions[index_arith].setActionIndex(1);
      //]
       
      if ((p == pearlrt::Fixed<15>(1)).getBoolean()) {
         //[ generated from ON
         sigActions[index_overfl].setActionIndex(2);
      //]
      }

      if ((p > pearlrt::Fixed<15>(5)).getBoolean()) {
         //[ generated from ON
         sigActions[index_overfl].setActionIndex(3);
         //]
      }
     
      //[ generated from ON
      sigActions[index_div0].setActionIndex(4);
      //]
      if ((p == pearlrt::Fixed<15>(11)).getBoolean()) {
         _k = pearlrt::Fixed<15>(10)/(_k-_k);
      }

      {
         pearlrt::Fixed<15> _i;    // loop counter is auto gen.
         for (_i = 1;
            (_i<=pearlrt::Fixed<15>(100)).getBoolean(); 
            _i = _i + pearlrt::Fixed<15>(1)) {
             _k =  _k * _k;
         }
      }
label_exit:
	/* nop */ ;
   //[ generated due to ON statements in PROC
   } catch (pearlrt::Signal & s) {
      int index = pearlrt::ScheduleSignalAction::getAction(
		&s, NBROFSIGACTIONS, sigActions);
      switch(index) {
          default: throw;   // this signal wasnot scheduled
          //[ generated from signal action #1 in PROC
          case 1:
             printf("proc x: arithmetic error (returning)\n");
             return; // if in PROC; else me->terminate(me);
          //]
          //[ generated from signal action #2 in PROC
          case 2:
             printf("proc x: Overflow occured (terminating)\n");
             me->terminate(me);
          //]
          //[ generated from signal action #3 in PROC
          case 3: 		 // signal action #3
              try {
                 // code for PUT 'PROC X: Overflow occured'
                 // TO console BY A, SKIP;
                 printf("proc x: Overflow occured (returning)\n");
               } catch (pearlrt::Signal &s) {
//                  if (!console.updateRST(s)) {
//                     throw;
//                  }
               }
               return; // if in PROC; else me->terminate(me);
          //]
          //[ generated from signal action #4 in PROC
	  case 4:               // signal action #4
             try {
                // code for PUT 'PROC X: divide by 0 (restarting)'
                // TO console BY A, SKIP;
                 printf("proc x: divide by 0 (restarting)\n");
              } catch (pearlrt::Signal &s) {
 //                if (!console.updateRST(s)) {
//                    throw;
//                 }
              }
              if ((p == pearlrt::Fixed<15>(6)).getBoolean()) {
	         sigGoto = index_exit;
                 goto restart;                 
              } else {
                 p = pearlrt::Fixed<15>(6);
	         sigGoto = index_restart;
                 goto restart;                 
              }
          //]
      } // end of switch
   } // end of catch
}


DCLTASK(TASK1,pearlrt::Prio(2),pearlrt::BitString<1>(1)) {
    pearlrt::Fixed<15> f;

    f = 0;
    _x(me, f);
    f = 11;
    _x(me, f);
    f = 10;
    _x(me, f);
    f = 1;
    _x(me, f);
}

