/*
 [A "BSD license"]
 Copyright (c) 2016 Rainer Mueller
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:

 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
 3. The name of the author may not be used to endorse or promote products
    derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * create C++ code for the detected elements
 * 
 * The order of definitions in the source code does not strictly depend on the
 * sequence in the PEARL code. The order is dominated by the sequence of
 * definition, which is overwritten if forward usage is detected.
 * 
 * @author mueller
 * 
 */
public class CodeGenerator {

	/*
	 * create to output file with to complete content
	 * 
	 * if errors like loops in definition are detected, an error message occurs
	 */
	public static void create(String outputFile) {
		PrintWriter file;
		int configItemNbr = 0;

		try {
			file = new PrintWriter(new FileWriter(outputFile));
		} catch (IOException e) {
			System.err.println("could not create output file");

			e.printStackTrace();
			return;
		}
		file.println("// [automatic generated by intermodule checker (imc) -- do not change ]");
		file.println("#include \"PearlIncludes.h\" ");

		boolean otherNamesNeeded;
		boolean newCodeCreated;
		do {
			otherNamesNeeded = false;
			newCodeCreated = false;
			for (int i = 0; i < SystemEntries.size(); i++) {
				SystemEntry un = SystemEntries.get(i);
				if (un.isDationSignalInterruptConnection()) {
					if (!un.codeIsCompleted()) {
						SystemEntry req = un.requiresOtherSystemEntry();
						if (req == null) {
							file.println("// " + un.getFileName() + ":"
									+ un.getLine());
							file.println(un.getCompleteCode());
							newCodeCreated = true;
						} else {
							// System.out.println("need "+req.getName()+" first");
							otherNamesNeeded = true;
						}
					}
				}
			}
		} while (otherNamesNeeded == true && newCodeCreated == true);
		if (otherNamesNeeded == true && newCodeCreated == false) {
			for (int i = 0; i < SystemEntries.size(); i++) {
				SystemEntry un = SystemEntries.get(i);
				if (un.isDationSignalInterruptConnection()) {
					if (!un.codeIsCompleted()) {
						Error.setLocation(un.getFileName(),  un.getLine());
						Error.error("circular dependency detected at the definition of "+un.getName());
						Error.append("needs "+un.requiresOtherSystemEntry().getName());
					}
				}
			}
			
		}

		file.println("\n//configuration items \nnamespace pearlconfig {");
		for (int i = 0; i < SystemEntries.size(); i++) {
			SystemEntry un = SystemEntries.get(i);
			if (un.getType() != null && un.getType().equals("configuration")) {
				file.println("// " + un.getFileName() + ":" + un.getLine());
				file.println(un.getCompleteCode4Config(configItemNbr++));
			}
		}
		file.println("};");
		file.close();

	}

}
