\htgt{Assignment} ::=\\
%%%\x \{ \{ \hlink{Name}$\S $Variable
%%%	 $\mid$ \hlink{Dereferentiation} 
%%%	$\mid$ \hlink{StringSelection}
%%%	$\mid$ \hlink{Name}$\S $Structure \}\\   
%%%\x \{ := $\mid$ = \} \} $^{...}$ \hlink{Expression} ;\\
\x \hlink{ScalarAssignment} $\mid$ \hlink{StructureAssignment}
 $\mid$ \hlink{RefProcAssignment}

