\begin{added}
\htgt{Association} ::=\\
\x  [ Association ]  -\ -\ - \\
\x        \{ \hlink{Identifier}$\S $UsernameOfConnectionProvider \\
\x \x   $\mid$ \hlink{Identifier}$\S $ConnectionProviderSystemName
         [ ( \hlink{ListOfConstants}) ] \} ;\\
\end{added}
