\htgt{Constant} ::=\\
\x \hlink{Integer} $\mid$ \hlink{FloatingPointNumber} \\
\x $\mid$ \hlink{BitStringConstant}  $\mid$  \hlink{CharacterStringConstant}\\
\x $\mid$ \hlink{TimeConstant} $\mid$  \hlink{DurationConstant}\\
\x $\mid$ \kw{NIL}

