\htgt{ConvertToStatement} ::= \\
\x {\bf CONVERT} \hlink{Expression} 
	[ , \hlink{Expression} ] $^{...}$ 
	{\bf TO} \hlink{Name}$\S $CharacterStringVariable\\
\x [ {\bf BY} \hlink{FormatOrPositionConvert} 
	[ , \hlink{FormatOrPositionConvert} ] $^{...}$ ] ;\\

