%%%\begin{removed}
%%%\htgt{LengthDefinition} ::=\\
%%%\x {\bf LENGTH} \{ {\bf FIXED $\mid$ FLOAT
%%%                    $\mid$ BIT $\mid$ CHARACTER $\mid$ CHAR} \}
%%%                ( \hlink{Precision} ) ;\\
%%%\end{removed}
\begin{tabbing}
\x \kw{LENGTH} \{ \= \{ \kw{FIXED} $\mid$ \kw{FLOAT} \} (\hlink{Precision})\kill

\htgt{LengthDefinition}::=\\
\x \kw{LENGTH} \{ \{ \kw{FIXED} $\mid$ \kw{FLOAT} \}
          (\hlink{Precision}) $\mid$ \\
\> 
\{ \kw{BIT} $\mid$ \kw{CHARACTER} $\mid$ \kw{CHAR} \} 
          (\hlink{LengthOfString}) \};
\end{tabbing}
