\htgt{ProcedureReferenceSpecification} ::= \\
\x \{ {\bf SPECIFY $\mid$ SPC} \} \hlink{OneIdentifierOrList} 
	[ \hlink{VirtualDimensionList} ] [ {\bf INV} ]\\
\x {\bf REF} \hlink{TypeProcedure} \hlink{GlobalAttribute};

