\htgt{ScalarDeclareDataSentence} ::=\\
%%%\x IdentifierDenotation
\x  \hlink{OneIdentifierOrList}
    [ {\bf INV} ] \hlink{TypeAttribute} [ \hlink{GlobalAttribute} ]\\
\x [ \hlink{InitialisationAttribute} ]

