\htgt{SequentialControlStatement} ::=\\
\x \hlink{IfStatement} $\mid$ \hlink{CaseStatement} $\mid$
	 \hlink{LoopStatement} $\mid$ \hlink{ExitStatement}\\
\x $\mid$ \hlink{ProcedureCall} $\mid$ \hlink{ReturnStatement}
	 $\mid$ \hlink{GoToStatement}\\
\x $\mid$ \hlink{EmptyStatement}

