%%%\begin{removed}
%%%SystemPart ::= \\
%%%\x {\bf SYSTEM} ;\\
%%%\x \x [ UserNameDeclaration$\S $ForDationInterruptOrSignal ] $^{...}$\\
%%%\end{removed}
%%%
\htgt{SystemPart} ::= \\
\x {\bf SYSTEM} ;\\
\x [  \{ \hlink{UserNameDeclaration}$\S $ForDationInterruptOrSignal
 $\mid$ \hlink{ConfigurationElement} \} $^{...}$ ]\\ 

