%%%%\begin{discuss}
%%%%REF INTERRUPT/IRPT, REF SIGNAL ok?
%%%% 8-2-2018: Discussion result: There seams to beno problem 
%%%%           to support references to interrupts and signals

\htgt{TypeReference} ::=\\
\x \kw{REF} \{ \\
\x [ \hlink{VirtualDimensionList} ] [ \kw{INV} ] 
	\{ \hlink{SimpleType} $\mid$ \hlink{StructuredType} \}\\
\x $\mid$ [ \hlink{VirtualDimensionList} ] 
	\{ \hlink{TypeDation} $\mid$ \kw{SEMA} $\mid$ \kw{BOLT} \}\\
\x $\mid$ \hlink{TypeProcedure} $\mid$ 
	\kw{TASK} $\mid$ \kw{INTERRUPT} $\mid$ \kw{IRPT} $\mid$ \kw{SIGNAL}\\
%%%$\mid$ \hlink{Type-VOID}
\x $\mid$ \kw{CHAR}( )\\
\x \}

%%%%\end{discuss}

