\begin{discuss}
REF INTERRUPT/IRPT, REF SIGNAL ok?

\htgt{TypeReference} ::=\\
\x {\bf REF} \\
\x \{ [ \hlink{VirtualDimensionList} ] [ {\bf INV} ] 
	\{ \hlink{SimpleType} $\mid$ \hlink{StructuredType} \}\\
\x \x $\mid$ [ \hlink{VirtualDimensionList} ] 
	\{ \hlink{TypeDation} $\mid$ {\bf SEMA $\mid$ BOLT} \}\\
\x \x $\mid$ \hlink{TypeProcedure} $\mid$ 
	{\bf TASK $\mid$ INTERRUPT $\mid$ IRPT $\mid$ SIGNAL}\\
\x \x 
%%%$\mid$ \hlink{Type-VOID}
 $\mid$ {\bf CHAR}( )\\
\x \}

\end{discuss}

