\begin{discuss}
REF INTERRUPT/IRPT, REF SIGNAL ok?

\begin{tabbing}
\x \{ \= [ \hlink{VirtualDimensionList} ] [ \kw{INV} ] \kill
\htgt{TypeReference} ::=\\
\x \kw{REF} \{ \\
\> [ \hlink{VirtualDimensionList} ] [ \kw{INV} ] 
	\{ \hlink{SimpleType} $\mid$ \hlink{StructuredType} \}\\
\> $\mid$ [ \hlink{VirtualDimensionList} ] 
	\{ \hlink{TypeDation} $\mid$ \kw{SEMA} $\mid$ \kw{BOLT} \}\\
\> $\mid$ \hlink{TypeProcedure} $\mid$ 
	\kw{TASK} $\mid$ \kw{INTERRUPT} $\mid$ \kw{IRPT} $\mid$ \kw{SIGNAL}\\
\> 
%%%$\mid$ \hlink{Type-VOID}
 $\mid$ \kw{CHAR}( )\\
\x \}

\end{tabbing}
\end{discuss}

