\begin{removed}
UserNameDeclaration ::=\\
\x Identifier$\S $UserName: Identifier$\S $SystemName [ ( nngz$\S $Index ) ]\\
\x \x [ $^*$ nngz$\S $Channel [ $^*$ nngz$\S $Position [ , nngz$\S $Width ] ] ];\\
\x $\mid$ Identifier$\S $UserName: Identifier$\S $SIGNAL-SystemName\\
\x \x [ ( Identifier$\S $ErrorNumber [ , Identifier$\S $ErrorNumber ] $^{...}$ ) ] ;\\
\end{removed}

\begin{added}
\htgt{UserNameDeclaration} ::=\\
\x \hlink{Identifier}$\S $UserName: [ \hlink{Identifier}$\S $Username -\,-\,- ]\\
\x \x \hlink{Identifier}$\S $DATION-SystemName [ ( \hlink{ListOfConstants} ) ];\\
\x \hlink{Identifier}$\S $UserName: \hlink{Identifier}$\S $SIGNAL-SystemName;\\
\x \hlink{Identifier}$\S $UserName: \hlink{Identifier}$\S $Interrupt-SystemName
		 [ ( \hlink{ListOfConstants} ) ];\\

\end{added}
