\htgt{WriteStatement} ::=\\
%%%\x {\bf WRITE} [ \{ \hlink{Expression} $\mid$ \hlink{Slice} \} 
%%%	[ , \{ \hlink{Expression} $\mid$ \hlink{Slice} \} ] $^{...}$ ]\\
%%%\x {\bf TO} \hlink{Name}$\S $Dation 
%%%	[ {\bf BY} \hlink{Position}
%%%		 [ , \hlink{Position} ] $^{...}$ ] ; \\
\x {\bf WRITE} [ \{ \hlink{Expression} $\mid$ \hlink{Slice} \} 
	[ , \{ \hlink{Expression} $\mid$ \hlink{Slice} \} ] $^{...}$ ]\\
\x {\bf TO} \hlink{Name}$\S $Dation [ {\bf BY} \hlink{Position} 
	[ , {\hlink{Position} ] $^{...}$ ] ;

      
