// [automatic generated by intermodule checker (imc) -- do not change ]
// 2018/01/09 16:40:03

#include "PearlIncludes.h" 



namespace pearlrt {
   int createSystemElements();
}

// enshure that the static (parametrized) objects are instanciated first
static int dummy = pearlrt::createSystemElements();

pearlrt::Device * d_stdout;	// hello.prl:8



namespace pearlrt {
   int createSystemElements() {

	// hello.prl:8
	static pearlrt::StdOut s_stdout;
	d_stdout = &s_stdout;

   return 0;
   }
}
