#!/bin/bash
if [ `id -u` -ne 0 ]
then
   echo "must be root for essential package installation"
   exit 1
fi

SystemKnown=0

grep "PRETTY_NAME=\"Debian GNU/Linux 8 (jessie)\"" /etc/os-release >/dev/null
rc=$?
if [ $rc -eq 0 ]
then
   echo "detected: Debian 8 jessie "
   AptPackageList="openjdk-7-jdk"
   AptPackageList+="gcc g++ git make gawk"
   AptPackageList+="flex libncurses5-dev"
   AptPackageList+="expat libexpat1-dev"
   AptDevelopers="astyle graphwiz doxygen"
   AptDevelopers+="libgtest-dev"
   SystemKnown=1
fi

grep "PRETTY_NAME=\"Raspbian GNU/Linux 8 (jessie)\"" /etc/os-release >/dev/null
rc=$?
if [ $rc -eq 0 ]
then
   echo "detected: Raspbain 8 jessie "
   AptPackageList="openjdk-7-jdk"
   AptPackageList+="flex libncurses5-dev"
   AptPackageList+="expat libexpat1-dev"
   AptDevelopers="astyle"
   SystemKnown=1
fi

grep "PRETTY_NAME=\"Raspbian GNU/Linux 9 (stretch)\"" /etc/os-release >/dev/null
rc=$?
if [ $rc -eq 0 ]
then
   echo "detected: Raspbain 9 stretch "
   AptPackageList="openjdk-8-jdk"
   AptPackageList+="flex libncurses5-dev"
   AptPackageList+="expat libexpat1-dev"
   AptDevelopers="astyle"
   SystemKnown=1
fi

if [ "$SystemKnown" -ne "1" ] 
then
   echo "host linux version not detected"
   cat /etc/os-release
   exit 1
fi

echo "required apt-packages"
echo $AptPackageList

if [ "$SystemKnown" -eq "1" ] 
then
   # common for all platforms
   wget http://www.antlr.org/download/antlr-4.5-complete.jar
   mv antlr-4.5-complete.jar /usr/local/lib/
   apt-get -q -y install $AptPackageList

   # set automatic 'y' for cpan/cpanm installation
   export PERL_MM_USE_DEFAULT=1
   cpan App::cpanminus
   cpanm Spreadsheet::Read
   cpanm Spreadsheet::ReadSXC

   # create dummy files in /usr/* as root and make them
   # mutable by everybody
   make prepare
fi

echo
echo "please log on as normal user and perform"
echo "    make install"
